### ISSUE TITLE
Support Async Observations

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-observation#112]
Similar to [async computes](https://canjs.com/doc/can-compute.async.html), we need some way of creating `Observation`s that can set their values asynchronously.

This would allow us to replace uses of `compute.async` with `Observation`s and fully support https://github.com/canjs/can-define/issues/149.

**Comment by phillipskevin** [comment]
This might be the same as https://github.com/canjs/can-observation/issues/84.

cc @christopherjbaker @justinbmeyer

**Comment by christopherjbaker** [comment]
The are definitely related. The deferred observables was one way to make an
asynchronous observable (and was implemented in RVM, which is what these
were for), though I think one that supports async functions would be much
nicer.

The specific need for these was RVM, and it was solved in the repo, do
these can be closed if the functionality is not otherwise desired.

**Comment by justinbmeyer** [comment]
I don't think this is needed anymore past 4.0. Creating your own observations is relatively easy now ... also can-observation-recorder gives one all the low-level mechanics someone needs.
